"""Начальная схема

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-11 09:51:39.558592
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campus')),
    sa.UniqueConstraint('name', name=op.f('uq_campus_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_campus_slug'))
    )
    op.create_table('constraint_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_key', sa.String(length=120), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constraint_rule'))
    )
    with op.batch_alter_table('constraint_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraint_rule_plugin_key'), ['plugin_key'], unique=False)

    op.create_table('external_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('plugin_key', sa.String(length=120), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_source')),
    sa.UniqueConstraint('name', name=op.f('uq_external_source_name'))
    )
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculty')),
    sa.UniqueConstraint('name', name=op.f('uq_faculty_name'))
    )
    op.create_table('plugin_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_key', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_state')),
    sa.UniqueConstraint('plugin_key', name=op.f('uq_plugin_state_plugin_key'))
    )
    op.create_table('schedule_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('semester', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('hard_score', sa.Integer(), nullable=False),
    sa.Column('soft_score', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['schedule_version.id'], name=op.f('fk_schedule_version_parent_id_schedule_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_version'))
    )
    with op.batch_alter_table('schedule_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_version_status'), ['status'], unique=False)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject')),
    sa.UniqueConstraint('name', name=op.f('uq_subject_name'))
    )
    op.create_table('bell_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('study_form', sa.String(length=20), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_bell_slot_campus_id_campus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bell_slot')),
    sa.UniqueConstraint('campus_id', 'study_form', 'slot_index', name=op.f('uq_bell_slot_campus_id'))
    )
    with op.batch_alter_table('bell_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bell_slot_campus_id'), ['campus_id'], unique=False)

    op.create_table('campus_travel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_campus_id', sa.Integer(), nullable=False),
    sa.Column('to_campus_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_campus_id'], ['campus.id'], name=op.f('fk_campus_travel_from_campus_id_campus'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_campus_id'], ['campus.id'], name=op.f('fk_campus_travel_to_campus_id_campus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campus_travel')),
    sa.UniqueConstraint('from_campus_id', 'to_campus_id', name=op.f('uq_campus_travel_from_campus_id'))
    )
    op.create_table('generation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('solver_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('hard_score', sa.Integer(), nullable=False),
    sa.Column('soft_score', sa.Integer(), nullable=False),
    sa.Column('placed', sa.Integer(), nullable=False),
    sa.Column('unplaced', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['schedule_version.id'], name=op.f('fk_generation_run_version_id_schedule_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_run'))
    )
    with op.batch_alter_table('generation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_run_version_id'), ['version_id'], unique=False)

    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_room_campus_id_campus'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room')),
    sa.UniqueConstraint('campus_id', 'code', name=op.f('uq_room_campus_id'))
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_campus_id'), ['campus_id'], unique=False)

    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_stream_campus_id_campus'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream')),
    sa.UniqueConstraint('name', name=op.f('uq_stream_name'))
    )
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_campus_id'), ['campus_id'], unique=False)

    op.create_table('student_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('study_form', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('split_flag', sa.Boolean(), nullable=False),
    sa.Column('subgroup_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('course BETWEEN 1 AND 6', name=op.f('ck_student_group_course_range')),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], name=op.f('fk_student_group_campus_id_campus'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], name=op.f('fk_student_group_faculty_id_faculty'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_group')),
    sa.UniqueConstraint('name', name=op.f('uq_student_group_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_student_group_slug'))
    )
    with op.batch_alter_table('student_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_group_campus_id'), ['campus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_group_faculty_id'), ['faculty_id'], unique=False)

    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('delivery_mode', sa.String(length=10), nullable=False),
    sa.Column('base_campus_id', sa.Integer(), nullable=True),
    sa.Column('max_pairs_per_day', sa.Integer(), nullable=False),
    sa.Column('max_pairs_per_week', sa.Integer(), nullable=False),
    sa.Column('external_source_id', sa.Integer(), nullable=True),
    sa.Column('external_ref', sa.String(length=160), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_campus_id'], ['campus.id'], name=op.f('fk_teacher_base_campus_id_campus'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['external_source_id'], ['external_source.id'], name=op.f('fk_teacher_external_source_id_external_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher')),
    sa.UniqueConstraint('slug', name=op.f('uq_teacher_slug'))
    )
    op.create_table('external_busy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('week_parity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['external_source.id'], name=op.f('fk_external_busy_source_id_external_source'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_external_busy_teacher_id_teacher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_busy'))
    )
    with op.batch_alter_table('external_busy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_busy_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_busy_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index('ix_external_busy_teacher_slot', ['teacher_id', 'day_of_week'], unique=False)

    op.create_table('stream_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['student_group.id'], name=op.f('fk_stream_member_group_id_student_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], name=op.f('fk_stream_member_stream_id_stream'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stream_member')),
    sa.UniqueConstraint('stream_id', 'group_id', name=op.f('uq_stream_member_stream_id'))
    )
    with op.batch_alter_table('stream_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_member_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stream_member_stream_id'), ['stream_id'], unique=False)

    op.create_table('subgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['student_group.id'], name=op.f('fk_subgroup_group_id_student_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subgroup')),
    sa.UniqueConstraint('group_id', 'index', name=op.f('uq_subgroup_group_id'))
    )
    with op.batch_alter_table('subgroup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subgroup_group_id'), ['group_id'], unique=False)

    op.create_table('teacher_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('slot_index', sa.Integer(), nullable=True),
    sa.Column('week_parity', sa.String(length=10), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_availability_teacher_id_teacher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_availability'))
    )
    with op.batch_alter_table('teacher_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_availability_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('teacher_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_request_teacher_id_teacher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_request'))
    )
    with op.batch_alter_table('teacher_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_request_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_user_teacher_id_teacher'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('login', name=op.f('uq_user_login'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_login', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_log_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('lesson_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('subgroup_id', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('lesson_type', sa.String(length=20), nullable=False),
    sa.Column('pairs_total', sa.Integer(), nullable=False),
    sa.Column('pairs_per_day_max', sa.Integer(), nullable=False),
    sa.Column('week_parity', sa.String(length=10), nullable=False),
    sa.Column('delivery_mode', sa.String(length=10), nullable=False),
    sa.Column('required_room_kind', sa.String(length=30), nullable=False),
    sa.Column('required_room_id', sa.Integer(), nullable=True),
    sa.Column('fixed_slot_index', sa.Integer(), nullable=True),
    sa.Column('fixed_day_of_week', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(group_id IS NOT NULL) + (subgroup_id IS NOT NULL) + (stream_id IS NOT NULL) = 1', name=op.f('ck_lesson_demand_exactly_one_target')),
    sa.CheckConstraint('pairs_total >= 1', name=op.f('ck_lesson_demand_pairs_positive')),
    sa.ForeignKeyConstraint(['group_id'], ['student_group.id'], name=op.f('fk_lesson_demand_group_id_student_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_room_id'], ['room.id'], name=op.f('fk_lesson_demand_required_room_id_room'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], name=op.f('fk_lesson_demand_stream_id_stream'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroup.id'], name=op.f('fk_lesson_demand_subgroup_id_subgroup'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_lesson_demand_subject_id_subject'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_lesson_demand_teacher_id_teacher'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_demand'))
    )
    with op.batch_alter_table('lesson_demand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_demand_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_demand_stream_id'), ['stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_demand_subgroup_id'), ['subgroup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_demand_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_demand_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('component_index', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('week_parity', sa.String(length=10), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['lesson_demand.id'], name=op.f('fk_assignment_demand_id_lesson_demand'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_assignment_room_id_room'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['schedule_version.id'], name=op.f('fk_assignment_version_id_schedule_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment'))
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_demand_id'), ['demand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_version_id'), ['version_id'], unique=False)
        batch_op.create_index('ix_assignment_version_slot', ['version_id', 'day_of_week', 'slot_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index('ix_assignment_version_slot')
        batch_op.drop_index(batch_op.f('ix_assignment_version_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_room_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_demand_id'))

    op.drop_table('assignment')
    with op.batch_alter_table('lesson_demand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_demand_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_demand_subject_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_demand_subgroup_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_demand_stream_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_demand_group_id'))

    op.drop_table('lesson_demand')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    op.drop_table('user')
    with op.batch_alter_table('teacher_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_request_teacher_id'))

    op.drop_table('teacher_request')
    with op.batch_alter_table('teacher_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_availability_teacher_id'))

    op.drop_table('teacher_availability')
    with op.batch_alter_table('subgroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subgroup_group_id'))

    op.drop_table('subgroup')
    with op.batch_alter_table('stream_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_member_stream_id'))
        batch_op.drop_index(batch_op.f('ix_stream_member_group_id'))

    op.drop_table('stream_member')
    with op.batch_alter_table('external_busy', schema=None) as batch_op:
        batch_op.drop_index('ix_external_busy_teacher_slot')
        batch_op.drop_index(batch_op.f('ix_external_busy_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_external_busy_source_id'))

    op.drop_table('external_busy')
    op.drop_table('teacher')
    with op.batch_alter_table('student_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_group_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_student_group_campus_id'))

    op.drop_table('student_group')
    with op.batch_alter_table('stream', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_campus_id'))

    op.drop_table('stream')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_campus_id'))

    op.drop_table('room')
    with op.batch_alter_table('generation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_run_version_id'))

    op.drop_table('generation_run')
    op.drop_table('campus_travel')
    with op.batch_alter_table('bell_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bell_slot_campus_id'))

    op.drop_table('bell_slot')
    op.drop_table('subject')
    with op.batch_alter_table('schedule_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_version_status'))

    op.drop_table('schedule_version')
    op.drop_table('plugin_state')
    op.drop_table('faculty')
    op.drop_table('external_source')
    with op.batch_alter_table('constraint_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraint_rule_plugin_key'))

    op.drop_table('constraint_rule')
    op.drop_table('campus')
    # ### end Alembic commands ###
